/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfrontino.adm.views.conf.general.products;

import com.openfrontino.adm.logic.products.ProductoDto;
import com.openfrontino.adm.logic.products.Productos;
import com.openfrontino.adm.logic.products.UnidadDto;
import com.openfrontino.tools.conection.ConnectionTool;
import com.openfrontino.tools.session.SessionDto;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author casc
 */
public class VenProducts extends javax.swing.JInternalFrame {

    SessionDto dtoSes;
    Connection con;
    //
    Productos clase;
    ProductoDto dto;
    List<UnidadDto> lstUnidades;

    /**
     * Creates new form VenProducts
     */
    public VenProducts(SessionDto _dtoSes) {
        initComponents();
        txtCodPro.setFocusTraversalKeysEnabled(false);
        dtoSes = _dtoSes;
        subConstructor();
        inicializarControles();
    }

    private Connection getCon() {
        try {
            if (con == null || con.isClosed()) {
                ConnectionTool conex = new ConnectionTool();
                if (!conex.connect(dtoSes.getDbhost(), dtoSes.getDbport(), dtoSes.getDbname(), dtoSes.getDbuser(),
                        dtoSes.getDbpassword()
                )) {
                    dtoSes = new SessionDto();
                    JOptionPane.showMessageDialog(null, "Error Conectando con Base de Datos", "Configuración", JOptionPane.INFORMATION_MESSAGE);
                    return null;
                }
                con = conex.getConexion();
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCatGen = new javax.swing.JButton();
        txtCodPro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodPro2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomPro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbStaPro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCbrPro = new javax.swing.JTextField();
        pnlMedida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbUndCom = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbUndVen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCosPro = new javax.swing.JTextField();
        txtPr2Pro = new javax.swing.JTextField();
        txtPr1Pro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPr3Pro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbPimPro = new javax.swing.JComboBox<>();
        txtFacPro = new javax.swing.JFormattedTextField();
        pnlInventario = new javax.swing.JPanel();
        chkMovPro = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtDisVen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblDisCom = new javax.swing.JLabel();
        chkObsPro = new javax.swing.JCheckBox();
        chkCreNod = new javax.swing.JCheckBox();
        chkCmbPro = new javax.swing.JCheckBox();
        chkSelPro = new javax.swing.JCheckBox();
        txtOrdPro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        btnCatGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_catalogo.png"))); // NOI18N
        btnCatGen.setMaximumSize(new java.awt.Dimension(24, 24));
        btnCatGen.setMinimumSize(new java.awt.Dimension(24, 24));
        btnCatGen.setPreferredSize(new java.awt.Dimension(24, 24));

        txtCodPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtCodPro.setPreferredSize(new java.awt.Dimension(150, 22));
        txtCodPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProActionPerformed(evt);
            }
        });
        txtCodPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyConsulta(evt);
            }
        });

        jLabel1.setText("Código");

        txtCodPro2.setMinimumSize(new java.awt.Dimension(150, 22));
        txtCodPro2.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel2.setText("Nombre");

        txtNomPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtNomPro.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel3.setText("Status");

        cmbStaPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel4.setText("Código de Barras");

        txtCbrPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtCbrPro.setPreferredSize(new java.awt.Dimension(150, 22));

        pnlMedida.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Unidades de Medida")));

        jLabel5.setText("Unidad Compra");

        cmbUndCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel6.setText("Unidad Venta");

        cmbUndVen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel7.setText("Conversión");

        jLabel8.setText("Costo");

        jLabel9.setText("Precio 1");

        txtCosPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtCosPro.setPreferredSize(new java.awt.Dimension(150, 22));

        txtPr2Pro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtPr2Pro.setPreferredSize(new java.awt.Dimension(150, 22));

        txtPr1Pro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtPr1Pro.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel10.setText("Precio 2");

        jLabel11.setText("Precio 3");

        txtPr3Pro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtPr3Pro.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel15.setText("Impuesto");

        cmbPimPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        txtFacPro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtFacPro.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout pnlMedidaLayout = new javax.swing.GroupLayout(pnlMedida);
        pnlMedida.setLayout(pnlMedidaLayout);
        pnlMedidaLayout.setHorizontalGroup(
            pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addGap(48, 48, 48)
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCosPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbUndCom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPr1Pro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(250, 250, 250))
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMedidaLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUndVen, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlMedidaLayout.createSequentialGroup()
                                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPr2Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbPimPro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPr3Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFacPro, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        pnlMedidaLayout.setVerticalGroup(
            pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbUndCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbUndVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtFacPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCosPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cmbPimPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPr1Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPr3Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtPr2Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        chkMovPro.setText("Manejo de Inventario");

        jLabel12.setText("Disponible Unidad de Venta");

        txtDisVen.setMinimumSize(new java.awt.Dimension(150, 22));
        txtDisVen.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel13.setText("Disponible Unidad de Venta");

        lblDisCom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisCom.setText("00,00");

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventarioLayout.createSequentialGroup()
                        .addComponent(chkMovPro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInventarioLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(52, 52, 52)
                        .addComponent(txtDisVen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkMovPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDisVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(lblDisCom))
                .addGap(43, 43, 43))
        );

        chkObsPro.setText("Observación al Facturar");

        chkCreNod.setText("Credito Fiscal No Deducible");

        chkCmbPro.setText("Combo");

        chkSelPro.setText("Selección Rápida");

        txtOrdPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtOrdPro.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel16.setText("Orden Seleccion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCmbPro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnlMedida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chkObsPro)
                                    .addGap(18, 18, 18)
                                    .addComponent(chkCreNod, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(chkSelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtOrdPro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCatGen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodPro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCbrPro, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                        .addComponent(cmbStaPro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCatGen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodPro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCbrPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbStaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(pnlMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkObsPro)
                    .addComponent(chkCreNod)
                    .addComponent(chkSelPro)
                    .addComponent(txtOrdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(10, 10, 10)
                .addComponent(chkCmbPro)
                .addContainerGap())
        );

        btnCatGen.getAccessibleContext().setAccessibleName("btnCatGen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProActionPerformed
        consultarProducto();
    }//GEN-LAST:event_txtCodProActionPerformed

    private void keyConsulta(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyConsulta
        if (evt.getKeyCode() == KeyEvent.VK_F2 || evt.getKeyCode() == KeyEvent.VK_TAB) {
            consultarProducto();
        }

    }//GEN-LAST:event_keyConsulta


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatGen;
    private javax.swing.JCheckBox chkCmbPro;
    private javax.swing.JCheckBox chkCreNod;
    private javax.swing.JCheckBox chkMovPro;
    private javax.swing.JCheckBox chkObsPro;
    private javax.swing.JCheckBox chkSelPro;
    private javax.swing.JComboBox<String> cmbPimPro;
    private javax.swing.JComboBox<String> cmbStaPro;
    private javax.swing.JComboBox<String> cmbUndCom;
    private javax.swing.JComboBox<String> cmbUndVen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDisCom;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlMedida;
    private javax.swing.JTextField txtCbrPro;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtCodPro2;
    private javax.swing.JTextField txtCosPro;
    private javax.swing.JTextField txtDisVen;
    private javax.swing.JFormattedTextField txtFacPro;
    private javax.swing.JTextField txtNomPro;
    private javax.swing.JTextField txtOrdPro;
    private javax.swing.JTextField txtPr1Pro;
    private javax.swing.JTextField txtPr2Pro;
    private javax.swing.JTextField txtPr3Pro;
    // End of variables declaration//GEN-END:variables

    private void consultarProducto() {
        System.out.println("do me search please");
        if (!txtCodPro.getText().trim().equals("")) {
            try {
                dto = clase.consultarProducto(0, txtCodPro.getText());

                if (dto == null) {
                    int result = JOptionPane.showConfirmDialog(this, "Codigo de Producto no existe \n"
                            + "Desea Agregar uno nuevo?", "Consulta",
                            JOptionPane.YES_NO_OPTION);
                    if (result == JOptionPane.YES_OPTION) {
                        habilitarControles();
                    }
                } else {
                    //TODO asignar
                    
                    habilitarControles();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void subConstructor() {
        clase = new Productos(getCon(), dtoSes);
        try {
            lstUnidades = clase.consultarUnidades();
            cmbUndCom.removeAllItems();
            cmbUndVen.removeAllItems();
            cmbPimPro.removeAllItems();
            for (int i = 0; i < lstUnidades.size(); i++) {
                UnidadDto dtoUnd = lstUnidades.get(i);
                cmbUndCom.addItem(dtoUnd.getCodUnd());
                cmbUndVen.addItem(dtoUnd.getCodUnd());

            }
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpGen()));
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpExe()));
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpRed()));
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpAdi()));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void inicializarControles() {
        txtCodPro.setText("");
        txtCodPro2.setText("");
        txtNomPro.setText("");
        txtCbrPro.setText("");
        cmbStaPro.setSelectedIndex(0);

        cmbUndCom.setSelectedIndex(0);
        cmbUndVen.setSelectedIndex(0);
        txtFacPro.setValue(new Float(0));
        txtCosPro.setText("0");
        cmbPimPro.setSelectedIndex(0);
        txtPr1Pro.setText("0");
        txtPr2Pro.setText("0");
        txtPr3Pro.setText("0");

        chkMovPro.setSelected(false);
        txtDisVen.setText("0");
        lblDisCom.setText("0");

        chkObsPro.setSelected(false);
        chkCreNod.setSelected(false);
        chkSelPro.setSelected(false);
        chkCmbPro.setSelected(false);
        txtOrdPro.setText("0");

        inhabilitarControles();
    }
    
    private void inhabilitarControles(){
        txtCodPro.setEnabled(true);
        btnCatGen.setEnabled(true);
        txtCodPro2.setEnabled(false);
        txtNomPro.setEnabled(false);
        txtCbrPro.setEnabled(false);
        cmbStaPro.setEnabled(false);
        cmbUndCom.setEnabled(false);
        cmbUndVen.setEnabled(false);
        txtFacPro.setEnabled(false);
        txtCosPro.setEnabled(false);
        cmbPimPro.setEnabled(false);
        txtPr1Pro.setEnabled(false);
        txtPr2Pro.setEnabled(false);
        txtPr3Pro.setEnabled(false);
        chkMovPro.setEnabled(false);
        txtDisVen.setEnabled(false);
        chkObsPro.setEnabled(false);
        chkCreNod.setEnabled(false);
        chkSelPro.setEnabled(false);
        txtOrdPro.setEnabled(false);
        chkCmbPro.setEnabled(false);
    }
    
      private void habilitarControles(){
        txtCodPro.setEnabled(false);
        btnCatGen.setEnabled(false);
        txtCodPro2.setEnabled(true);
        txtNomPro.setEnabled(true);
        txtCbrPro.setEnabled(true);
        cmbStaPro.setEnabled(true);
        cmbUndCom.setEnabled(true);
        cmbUndVen.setEnabled(true);
        txtFacPro.setEnabled(true);
        txtCosPro.setEnabled(true);
        cmbPimPro.setEnabled(true);
        txtPr1Pro.setEnabled(true);
        txtPr2Pro.setEnabled(true);
        txtPr3Pro.setEnabled(true);
        chkMovPro.setEnabled(true);
        txtDisVen.setEnabled(true);
        chkObsPro.setEnabled(true);
        chkCreNod.setEnabled(true);
        chkSelPro.setEnabled(true);
        txtOrdPro.setEnabled(true);
        chkCmbPro.setEnabled(true);
    }
}
