/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfrontino.adm.views.conf.general.products;

import com.openfrontino.adm.logic.products.ProductoDto;
import com.openfrontino.adm.logic.products.Productos;
import com.openfrontino.adm.logic.products.UnidadDto;
import com.openfrontino.tools.conection.ConnectionTool;
import com.openfrontino.tools.format.Formateo;
import com.openfrontino.tools.session.SessionDto;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author casc
 */
public class VenProductos extends javax.swing.JInternalFrame {

    SessionDto dtoSes;
    Connection con;
    //
    private final String SEP_MIL;
    private final String SEP_DEC;
    //
    Productos clase;
    ProductoDto dto;
    List<UnidadDto> lstUnidades;

    /**
     * Creates new form VenProducts
     */
    public VenProductos(SessionDto _dtoSes) {
        initComponents();
        txtCodPro.setFocusTraversalKeysEnabled(false);
        dtoSes = _dtoSes;
        SEP_DEC = dtoSes.getSeparadordecimal();
        SEP_MIL = dtoSes.getSeparadormiles();
        subConstructor();
        inicializarControles();
    }

    private Connection getCon() {
        try {
            if (con == null || con.isClosed()) {
                ConnectionTool conex = new ConnectionTool();
                if (!conex.connect(dtoSes.getDbhost(), dtoSes.getDbport(), dtoSes.getDbname(), dtoSes.getDbuser(),
                        dtoSes.getDbpassword()
                )) {
                    dtoSes = new SessionDto();
                    JOptionPane.showMessageDialog(null, "Error Conectando con Base de Datos", "Configuración", JOptionPane.INFORMATION_MESSAGE);
                    return null;
                }
                con = conex.getConexion();
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCatGen = new javax.swing.JButton();
        txtCodPro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodPro2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomPro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbStaPro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCbrPro = new javax.swing.JTextField();
        pnlMedida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbUndCom = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbUndVen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbPimPro = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtUt1Pro = new javax.swing.JTextField();
        txtPr1Pro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtUt3Pro = new javax.swing.JTextField();
        txtPr3Pro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtUt2Pro = new javax.swing.JTextField();
        txtPr2Pro = new javax.swing.JTextField();
        chkActPre = new javax.swing.JCheckBox();
        txtCosPro = new javax.swing.JTextField();
        txtFacPro = new javax.swing.JTextField();
        pnlInventario = new javax.swing.JPanel();
        chkMovPro = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDisCom = new javax.swing.JLabel();
        txtDisVen = new javax.swing.JTextField();
        txtPesPro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chkObsPro = new javax.swing.JCheckBox();
        chkCreNod = new javax.swing.JCheckBox();
        chkCmbPro = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        chkSelPro = new javax.swing.JCheckBox();
        txtOrdPro = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Registro de Productos");

        btnCatGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_catalogo.png"))); // NOI18N
        btnCatGen.setMaximumSize(new java.awt.Dimension(24, 24));
        btnCatGen.setMinimumSize(new java.awt.Dimension(24, 24));
        btnCatGen.setPreferredSize(new java.awt.Dimension(24, 24));

        txtCodPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtCodPro.setPreferredSize(new java.awt.Dimension(150, 22));
        txtCodPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProActionPerformed(evt);
            }
        });
        txtCodPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyConsulta(evt);
            }
        });

        jLabel1.setText("Código");

        txtCodPro2.setMinimumSize(new java.awt.Dimension(150, 22));
        txtCodPro2.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel2.setText("Nombre");

        txtNomPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtNomPro.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel3.setText("Status");

        cmbStaPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel4.setText("Código de Barras");

        txtCbrPro.setMinimumSize(new java.awt.Dimension(150, 22));
        txtCbrPro.setPreferredSize(new java.awt.Dimension(150, 22));

        pnlMedida.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Unidades de Medida")));

        jLabel5.setText("Unidad Compra");

        cmbUndCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel6.setText("Unidad Venta");

        cmbUndVen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel7.setText("Factor Conversión Entre Unidades");

        jLabel8.setText("Costo en Compras");

        jLabel15.setText("Impuesto");

        cmbPimPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio 1 (Sin IVA)"));

        jLabel18.setText("% Uti.");

        jLabel19.setText("Precio");

        txtUt1Pro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtUt1Pro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUt1ProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUt1ProFocusLost(evt);
            }
        });

        txtPr1Pro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtPr1Pro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPr1ProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPr1ProFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUt1Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtPr1Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtUt1Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPr1Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio 3 (Sin IVA)"));

        jLabel20.setText("% Uti.");

        jLabel21.setText("Precio");

        txtUt3Pro.setMinimumSize(new java.awt.Dimension(4, 22));
        txtUt3Pro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtUt3Pro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUt3ProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUt3ProFocusLost(evt);
            }
        });

        txtPr3Pro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtPr3Pro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPr3ProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPr3ProFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUt3Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPr3Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtUt3Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPr3Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio 2 (Sin IVA)"));

        jLabel22.setText("% Uti.");

        jLabel23.setText("Precio");

        txtUt2Pro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtUt2Pro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUt2ProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUt2ProFocusLost(evt);
            }
        });

        txtPr2Pro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtPr2Pro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPr2ProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPr2ProFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUt2Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPr2Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(txtUt2Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPr2Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkActPre.setText("Actualización de Precios Automatica en Compras");

        txtCosPro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCosPro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtCosPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCosProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCosProFocusLost(evt);
            }
        });

        txtFacPro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtFacPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFacProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFacProFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlMedidaLayout = new javax.swing.GroupLayout(pnlMedida);
        pnlMedida.setLayout(pnlMedidaLayout);
        pnlMedidaLayout.setHorizontalGroup(
            pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106)
                        .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUndCom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCosPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMedidaLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(cmbPimPro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbUndVen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMedidaLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFacPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(chkActPre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMedidaLayout.setVerticalGroup(
            pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMedidaLayout.createSequentialGroup()
                                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cmbUndCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMedidaLayout.createSequentialGroup()
                                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbUndVen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFacPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel8)
                            .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbPimPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkActPre))
                            .addComponent(txtCosPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMedidaLayout.createSequentialGroup()
                        .addGroup(pnlMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        chkMovPro.setText("Manejo de Inventario");

        jLabel12.setText("Disponible Unidad de Venta");

        jLabel13.setText("Disponible Unidad de Compra");

        lblDisCom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisCom.setText("00,00");

        txtDisVen.setPreferredSize(new java.awt.Dimension(70, 22));
        txtDisVen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDisVenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDisVenFocusLost(evt);
            }
        });

        txtPesPro.setPreferredSize(new java.awt.Dimension(70, 22));
        txtPesPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesProFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesProFocusLost(evt);
            }
        });

        jLabel9.setText("Peso Und. Venta");

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkMovPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisVen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDisCom, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtPesPro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMovPro)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(lblDisCom)
                    .addComponent(txtDisVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkObsPro.setText("Observación al Facturar");

        chkCreNod.setText("Credito Fiscal No Deducible");

        chkCmbPro.setText("Combo");

        jLabel16.setText("Orden Seleccion");

        chkSelPro.setText("Selección Rápida");

        txtOrdPro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtOrdPro.setPreferredSize(new java.awt.Dimension(135, 22));
        txtOrdPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cambiarSeparadorDecimal(evt);
            }
        });

        jButton1.setText("Guardar");

        jButton2.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jButton1)
                        .addGap(134, 134, 134)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkCmbPro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkObsPro)
                        .addGap(18, 18, 18)
                        .addComponent(chkCreNod, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomPro, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCatGen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodPro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCbrPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbStaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(pnlMedida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCatGen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodPro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCbrPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbStaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addComponent(pnlMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkObsPro)
                    .addComponent(chkCreNod)
                    .addComponent(jLabel16)
                    .addComponent(chkSelPro)
                    .addComponent(txtOrdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(chkCmbPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        btnCatGen.getAccessibleContext().setAccessibleName("btnCatGen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProActionPerformed
        consultarProducto();
    }//GEN-LAST:event_txtCodProActionPerformed

    private void keyConsulta(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyConsulta
        if (evt.getKeyCode() == KeyEvent.VK_F2 || evt.getKeyCode() == KeyEvent.VK_TAB) {
            consultarProducto();
        }

    }//GEN-LAST:event_keyConsulta

    private void cambiarSeparadorDecimal(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cambiarSeparadorDecimal
        char c = evt.getKeyChar();
        char sep = ',';
        char nosep = '.';
        if (dtoSes.getSeparadordecimal() != null) {
            sep = dtoSes.getSeparadordecimal().charAt(0);
            if (sep == ',') {
                nosep = '.';
            } else {
                nosep = ',';
            }
        }
        if (c == nosep) {
            evt.setKeyChar(sep);
        }

    }//GEN-LAST:event_cambiarSeparadorDecimal

    private void txtCosProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCosProFocusLost
        txtCosPro.setText(dtoSes.formatearString(txtCosPro.getText()));
        double cospro = dtoSes.valorDoubleFomateado(txtCosPro.getText());
        if (cospro > 0) {
            double ut1 = dtoSes.valorDoubleFomateado(txtUt1Pro.getText());
            double ut2 = dtoSes.valorDoubleFomateado(txtUt2Pro.getText());
            double ut3 = dtoSes.valorDoubleFomateado(txtUt3Pro.getText());
            txtPr1Pro.setText(dtoSes.numeroFormateadoStr(cospro * ((ut1 / 100) + 1)));
            txtPr2Pro.setText(dtoSes.numeroFormateadoStr(cospro * ((ut2 / 100) + 1)));
            txtPr3Pro.setText(dtoSes.numeroFormateadoStr(cospro * ((ut3 / 100) + 1)));
        }
    }//GEN-LAST:event_txtCosProFocusLost

    private void txtCosProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCosProFocusGained
        txtCosPro.setText(dtoSes.quitarFormatoString(txtCosPro.getText()));
        txtCosPro.selectAll();
    }//GEN-LAST:event_txtCosProFocusGained

    private void txtFacProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFacProFocusGained
        txtFacPro.setText(dtoSes.quitarFormatoString(txtFacPro.getText()));
        txtFacPro.selectAll();
    }//GEN-LAST:event_txtFacProFocusGained

    private void txtFacProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFacProFocusLost
        txtFacPro.setText(dtoSes.formatearString(txtFacPro.getText()));
        calcularConversion();

    }//GEN-LAST:event_txtFacProFocusLost

    private void txtUt1ProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUt1ProFocusGained
        txtUt1Pro.setText(dtoSes.quitarFormatoString(txtUt1Pro.getText()));
        txtUt1Pro.selectAll();
    }//GEN-LAST:event_txtUt1ProFocusGained

    private void txtUt1ProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUt1ProFocusLost
        txtUt1Pro.setText(dtoSes.formatearString(txtUt1Pro.getText()));

        double cospro = dtoSes.valorDoubleFomateado(txtCosPro.getText());
        if (cospro > 0) {
            double ut1 = dtoSes.valorDoubleFomateado(txtUt1Pro.getText());
            txtPr1Pro.setText(dtoSes.numeroFormateadoStr(cospro * ((ut1 / 100) + 1)));
        }

    }//GEN-LAST:event_txtUt1ProFocusLost

    private void txtPr1ProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPr1ProFocusGained
        txtPr1Pro.setText(dtoSes.quitarFormatoString(txtPr1Pro.getText()));
        txtPr1Pro.selectAll();
    }//GEN-LAST:event_txtPr1ProFocusGained

    private void txtPr1ProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPr1ProFocusLost
        txtPr1Pro.setText(dtoSes.formatearString(txtPr1Pro.getText()));

        double cospro = dtoSes.valorDoubleFomateado(txtCosPro.getText());
        if (cospro > 0) {
            double pr1 = dtoSes.valorDoubleFomateado(txtPr1Pro.getText());
            double ut1 = ((pr1 * 100) / cospro) - 100;
            txtUt1Pro.setText(dtoSes.numeroFormateadoStr(ut1));
        }
    }//GEN-LAST:event_txtPr1ProFocusLost

    private void txtUt2ProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUt2ProFocusGained
        txtUt2Pro.setText(dtoSes.quitarFormatoString(txtUt2Pro.getText()));
        txtUt2Pro.selectAll();
    }//GEN-LAST:event_txtUt2ProFocusGained

    private void txtUt2ProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUt2ProFocusLost
        txtUt2Pro.setText(dtoSes.formatearString(txtUt2Pro.getText()));

        double cospro = dtoSes.valorDoubleFomateado(txtCosPro.getText());
        if (cospro > 0) {
            double ut2 = dtoSes.valorDoubleFomateado(txtUt2Pro.getText());
            txtPr2Pro.setText(dtoSes.numeroFormateadoStr(cospro * ((ut2 / 100) + 1)));
        }
    }//GEN-LAST:event_txtUt2ProFocusLost

    private void txtPr2ProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPr2ProFocusGained
        txtPr2Pro.setText(dtoSes.quitarFormatoString(txtPr2Pro.getText()));
        txtPr2Pro.selectAll();
    }//GEN-LAST:event_txtPr2ProFocusGained

    private void txtPr2ProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPr2ProFocusLost
        txtPr2Pro.setText(dtoSes.formatearString(txtPr2Pro.getText()));

        double cospro = dtoSes.valorDoubleFomateado(txtCosPro.getText());
        if (cospro > 0) {
            double pr2 = dtoSes.valorDoubleFomateado(txtPr2Pro.getText());
            double ut2 = ((pr2 * 100) / cospro) - 100;
            txtUt2Pro.setText(dtoSes.numeroFormateadoStr(ut2));
        }
    }//GEN-LAST:event_txtPr2ProFocusLost

    private void txtUt3ProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUt3ProFocusGained
        txtUt3Pro.setText(dtoSes.quitarFormatoString(txtUt3Pro.getText()));
        txtUt3Pro.selectAll();
    }//GEN-LAST:event_txtUt3ProFocusGained

    private void txtUt3ProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUt3ProFocusLost
        txtUt3Pro.setText(dtoSes.formatearString(txtUt3Pro.getText()));

        double cospro = dtoSes.valorDoubleFomateado(txtCosPro.getText());
        if (cospro > 0) {
            double ut3 = dtoSes.valorDoubleFomateado(txtUt3Pro.getText());
            txtPr3Pro.setText(dtoSes.numeroFormateadoStr(cospro * ((ut3 / 100) + 1)));
        }
    }//GEN-LAST:event_txtUt3ProFocusLost

    private void txtPr3ProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPr3ProFocusGained
        txtPr3Pro.setText(dtoSes.quitarFormatoString(txtPr3Pro.getText()));
        txtPr3Pro.selectAll();
    }//GEN-LAST:event_txtPr3ProFocusGained

    private void txtPr3ProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPr3ProFocusLost
        txtPr3Pro.setText(dtoSes.formatearString(txtPr3Pro.getText()));

        double cospro = dtoSes.valorDoubleFomateado(txtCosPro.getText());
        if (cospro > 0) {
            double pr3 = dtoSes.valorDoubleFomateado(txtPr3Pro.getText());
            double ut3 = ((pr3 * 100) / cospro) - 100;
            txtUt3Pro.setText(dtoSes.numeroFormateadoStr(ut3));
        }
    }//GEN-LAST:event_txtPr3ProFocusLost

    private void txtDisVenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDisVenFocusGained
        txtDisVen.setText(dtoSes.quitarFormatoString(txtDisVen.getText()));
        txtDisVen.selectAll();
    }//GEN-LAST:event_txtDisVenFocusGained

    private void txtDisVenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDisVenFocusLost
        txtDisVen.setText(dtoSes.formatearString(txtDisVen.getText()));

        calcularConversion();

    }//GEN-LAST:event_txtDisVenFocusLost

    private void txtPesProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesProFocusGained
        txtPesPro.setText(dtoSes.quitarFormatoString(txtPesPro.getText()));
        txtPesPro.selectAll();
    }//GEN-LAST:event_txtPesProFocusGained

    private void txtPesProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesProFocusLost
        txtPesPro.setText(dtoSes.formatearString(txtPesPro.getText()));
    }//GEN-LAST:event_txtPesProFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatGen;
    private javax.swing.JCheckBox chkActPre;
    private javax.swing.JCheckBox chkCmbPro;
    private javax.swing.JCheckBox chkCreNod;
    private javax.swing.JCheckBox chkMovPro;
    private javax.swing.JCheckBox chkObsPro;
    private javax.swing.JCheckBox chkSelPro;
    private javax.swing.JComboBox<String> cmbPimPro;
    private javax.swing.JComboBox<String> cmbStaPro;
    private javax.swing.JComboBox<String> cmbUndCom;
    private javax.swing.JComboBox<String> cmbUndVen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDisCom;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlMedida;
    private javax.swing.JTextField txtCbrPro;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtCodPro2;
    private javax.swing.JTextField txtCosPro;
    private javax.swing.JTextField txtDisVen;
    private javax.swing.JTextField txtFacPro;
    private javax.swing.JTextField txtNomPro;
    private javax.swing.JFormattedTextField txtOrdPro;
    private javax.swing.JTextField txtPesPro;
    private javax.swing.JTextField txtPr1Pro;
    private javax.swing.JTextField txtPr2Pro;
    private javax.swing.JTextField txtPr3Pro;
    private javax.swing.JTextField txtUt1Pro;
    private javax.swing.JTextField txtUt2Pro;
    private javax.swing.JTextField txtUt3Pro;
    // End of variables declaration//GEN-END:variables

    private void consultarProducto() {
        System.out.println("do me search please");
        if (!txtCodPro.getText().trim().equals("")) {
            try {
                dto = clase.consultarProducto(0, txtCodPro.getText());

                if (dto == null) {
                    int result = JOptionPane.showConfirmDialog(this, "Codigo de Producto no existe \n"
                            + "Desea Agregar uno nuevo?", "Consulta",
                            JOptionPane.YES_NO_OPTION);
                    if (result == JOptionPane.YES_OPTION) {
                        habilitarControles();
                    }
                } else {
                    //TODO asignar

                    habilitarControles();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void subConstructor() {
        clase = new Productos(getCon(), dtoSes);
        try {
            lstUnidades = clase.consultarUnidades();
            cmbUndCom.removeAllItems();
            cmbUndVen.removeAllItems();
            cmbPimPro.removeAllItems();
            for (int i = 0; i < lstUnidades.size(); i++) {
                UnidadDto dtoUnd = lstUnidades.get(i);
                cmbUndCom.addItem(dtoUnd.getCodUnd());
                cmbUndVen.addItem(dtoUnd.getCodUnd());

            }
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpGen()));
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpExe()));
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpRed()));
            cmbPimPro.addItem(String.valueOf(dtoSes.getImpAdi()));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void inicializarControles() {
        txtCodPro.setText("");
        txtCodPro2.setText("");
        txtNomPro.setText("");
        txtCbrPro.setText("");
        cmbStaPro.setSelectedIndex(0);

        cmbUndCom.setSelectedIndex(0);
        cmbUndVen.setSelectedIndex(0);
        txtFacPro.setText("1");
        txtCosPro.setText("0");
        cmbPimPro.setSelectedIndex(0);
        txtPr1Pro.setText("0");
        txtPr2Pro.setText("0");
        txtPr3Pro.setText("0");
        txtUt1Pro.setText("0");
        txtUt2Pro.setText("0");
        txtUt3Pro.setText("0");
        txtDisVen.setText("0");

        chkMovPro.setSelected(false);
        lblDisCom.setText("0");

        chkObsPro.setSelected(false);
        chkCreNod.setSelected(false);
        chkActPre.setSelected(false);
        chkSelPro.setSelected(false);
        chkCmbPro.setSelected(false);
        txtOrdPro.setValue(new Integer(0));

        inhabilitarControles();
    }

    private void inhabilitarControles() {
        txtCodPro.setEnabled(true);
        btnCatGen.setEnabled(true);
        txtCodPro2.setEnabled(false);
        txtNomPro.setEnabled(false);
        txtCbrPro.setEnabled(false);
        cmbStaPro.setEnabled(false);
        cmbUndCom.setEnabled(false);
        cmbUndVen.setEnabled(false);
        txtFacPro.setEnabled(false);
        txtCosPro.setEnabled(false);
        cmbPimPro.setEnabled(false);
        txtPr1Pro.setEnabled(false);
        txtPr2Pro.setEnabled(false);
        txtPr3Pro.setEnabled(false);
        txtUt1Pro.setEnabled(false);
        txtUt2Pro.setEnabled(false);
        txtUt3Pro.setEnabled(false);
        chkMovPro.setEnabled(false);
        txtDisVen.setEnabled(false);
        chkObsPro.setEnabled(false);
        chkCreNod.setEnabled(false);
        chkActPre.setEnabled(false);
        txtOrdPro.setEnabled(false);
        chkCmbPro.setEnabled(false);
    }

    private void habilitarControles() {
        txtCodPro.setEnabled(false);
        btnCatGen.setEnabled(false);
        txtCodPro2.setEnabled(true);
        txtNomPro.setEnabled(true);
        txtCbrPro.setEnabled(true);
        cmbStaPro.setEnabled(true);
        cmbUndCom.setEnabled(true);
        cmbUndVen.setEnabled(true);
        txtFacPro.setEnabled(true);
        txtCosPro.setEnabled(true);
        cmbPimPro.setEnabled(true);
        txtPr1Pro.setEnabled(true);
        txtPr2Pro.setEnabled(true);
        txtPr3Pro.setEnabled(true);
        txtUt1Pro.setEnabled(true);
        txtUt2Pro.setEnabled(true);
        txtUt3Pro.setEnabled(true);
        chkMovPro.setEnabled(true);
        txtDisVen.setEnabled(true);
        chkObsPro.setEnabled(true);
        chkCreNod.setEnabled(true);
        chkActPre.setEnabled(true);
        txtOrdPro.setEnabled(true);
        chkCmbPro.setEnabled(true);
    }

    private void asignarDto() {
        dto.setCodPro(txtCodPro2.getText());
        dto.setNomPro(txtNomPro.getText());
        dto.setCbrPro(txtCbrPro.getText());
        dto.setStaPro((char) (cmbStaPro.getSelectedIndex() + 1));
        dto.setUndCom(lstUnidades.get(cmbUndCom.getSelectedIndex()));
        dto.setUndVen(lstUnidades.get(cmbUndVen.getSelectedIndex()));

        dto.setFacPro(dtoSes.valorDoubleFomateado(txtFacPro.getText()));
        dto.setCosPro(dtoSes.valorDoubleFomateado(txtCosPro.getText()));
        dto.setPimPro(Float.valueOf(cmbPimPro.getSelectedItem().toString()));
        dto.setActPre(chkActPre.isSelected());

        dto.setUt1Pro(dtoSes.valorDoubleFomateado(txtUt1Pro.getText()));
        dto.setUt2Pro(dtoSes.valorDoubleFomateado(txtUt2Pro.getText()));
        dto.setUt3Pro(dtoSes.valorDoubleFomateado(txtUt3Pro.getText()));
        dto.setPr1Pro(dtoSes.valorDoubleFomateado(txtPr1Pro.getText()));
        dto.setPr2Pro(dtoSes.valorDoubleFomateado(txtPr2Pro.getText()));
        dto.setPr3Pro(dtoSes.valorDoubleFomateado(txtPr3Pro.getText()));
        dto.setMovPro(chkMovPro.isSelected());
        dto.setDisVen(dtoSes.valorDoubleFomateado(txtDisVen.getText()));
        dto.setDisCom(dtoSes.valorDoubleFomateado(lblDisCom.getText()));
        dto.setPesPro(dtoSes.valorDoubleFomateado(txtPesPro.getText()));
        dto.setObsPro(chkObsPro.isSelected());
        dto.setCreNod(chkCreNod.isSelected());
        dto.setSelPro(chkSelPro.isSelected());
        dto.setOrdPro(((Number) txtOrdPro.getValue()).intValue());
        dto.setCmbPro(chkCmbPro.isSelected());
    }

    private void calcularConversion() {
        double facpro = dtoSes.valorDoubleFomateado(txtFacPro.getText());
        if (facpro <= 0) {
            txtFacPro.setText("1");
            facpro = 1;
        }
        double disven = dtoSes.valorDoubleFomateado(txtDisVen.getText());
        lblDisCom.setText(dtoSes.numeroFormateadoStr(disven * facpro));
    }

}
