/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfrontino.adm.views.security;

import com.openfrontino.tools.conection.ConnectionTool;
import com.openfrontino.tools.session.Session;
import com.openfrontino.tools.session.SessionDto;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author casc
 */
public class VenLogin extends javax.swing.JDialog {

    private SessionDto dtoSes;

    /**
     * Creates new form VenLogin
     */
    public VenLogin(java.awt.Frame parent, boolean modal, SessionDto _dtoSes) {
        super(parent, modal);
        initComponents();
        //Para default
        JRootPane rootPanel = SwingUtilities.getRootPane(btnLogin);
        rootPanel.setDefaultButton(btnLogin);
        
        dtoSes = _dtoSes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OpenFrontinoLogin");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 69, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 131;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 47, 0, 63);
        getContentPane().add(txtLogin, gridBagConstraints);

        jLabel2.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 69, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 131;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 47, 0, 63);
        getContentPane().add(txtPassword, gridBagConstraints);

        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 69, 27, 63);
        getContentPane().add(btnLogin, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (this.txtLogin.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Nombre de Usuario", "Validacion de Datos", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (this.txtPassword.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Contraseña", "Validacion de Datos", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ConnectionTool conex = new ConnectionTool();
        if (!conex.connect(dtoSes.getDbhost(), dtoSes.getDbport(), dtoSes.getDbname(), dtoSes.getDbuser(),
                dtoSes.getDbpassword()
        )) {
            dtoSes = new SessionDto();
            JOptionPane.showMessageDialog(null, "Error Conectando con Base de Datos", "Configuración", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Connection con = conex.getConexion();
        boolean commit = false;
        try {
            Session ses = new Session();
            ses.setCon(con);
            //Validar Usuario
            StringBuilder password = new StringBuilder();
            for (int i = 0; i < this.txtPassword.getPassword().length; i++) {
                password.append(this.txtPassword.getPassword()[i]);
            }
            dtoSes.setDtoUsu(ses.logearUsuario(this.txtLogin.getText(), password.toString()));
            if (dtoSes.getDtoUsu() == null) {
                JOptionPane.showMessageDialog(null, "Datos de Usuario Incorrectos", "Validacion de Datos", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            this.dispose();
        } catch (Exception ex) {
            ConnectionTool.rollBackTrans(con);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Configuración", JOptionPane.ERROR_MESSAGE);
        } finally {
            ConnectionTool.killConnection(con);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
