/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openfrontino.adm.views;

import com.openfrontino.adm.views.conf.VenSetup;
import com.openfrontino.adm.views.conf.general.products.VenProductos;
import com.openfrontino.adm.views.security.VenLogin;
import com.openfrontino.tools.session.SessionDto;
import javax.swing.JOptionPane;

/**
 *
 * @author casc
 */
public class VenFrontinoAdm extends javax.swing.JFrame {

    SessionDto dtoSes;
    private boolean primera = false;
    private boolean logear = false;

    /**
     *
     * @param _dtoSes
     */
    public VenFrontinoAdm(SessionDto _dtoSes) {
        initComponents();
        dtoSes = _dtoSes;
        if (dtoSes == null) {
            primera = true;
            dtoSes = new SessionDto();
            VenSetup ven = new VenSetup(this, true, dtoSes);
            ven.setLocationByPlatform(true);
            ven.setVisible(true);
        }
        if (dtoSes.getDtoUsu() == null) {
            logear = true;
            VenLogin ven = new VenLogin(this, true, dtoSes);
            ven.setLocationByPlatform(true);
            ven.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menOpenFrontino = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenFrontino");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        menOpenFrontino.setText("General");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menOpenFrontino.add(jMenuItem1);

        jMenuBar1.add(menOpenFrontino);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (primera) {
            if (dtoSes.getDtoEmp() == null && dtoSes.getDtoUsu() == null) {
                JOptionPane.showMessageDialog(null, "No se ha podido configurar OpenFrontino", "Configuración", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            primera = false;
        }
        if (logear) {
            if (dtoSes.getDtoUsu() == null) {
                JOptionPane.showMessageDialog(null, "Lo sentimos, no se ha iniciado sesión", "Login", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VenProductos venprod = new VenProductos(dtoSes);

        venprod.setVisible(true);
        desktop.add(venprod);
        try {
            venprod.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menOpenFrontino;
    // End of variables declaration//GEN-END:variables
}
